-- MySQL Script generated by MySQL Workbench
-- wto, 22 maj 2018, 10:44:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WeatherStations
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WeatherStations
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WeatherStations` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `WeatherStations` ;

-- -----------------------------------------------------
-- Table `WeatherStations`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WeatherStations`.`users` (
  `IDuser` INT NOT NULL AUTO_INCREMENT,
  `Adres_email` VARCHAR(25) NOT NULL,
  `Password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IDuser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WeatherStations`.`notifiaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WeatherStations`.`notifiaction` (
  `IDnotification` INT NOT NULL,
  `users_IDuser` INT NOT NULL,
  `AlarmSignal` VARCHAR(20) NOT NULL,
  `TriggerMin` DOUBLE NULL,
  `TriggerMax` DOUBLE NULL,
  PRIMARY KEY (`IDnotification`, `users_IDuser`),
  INDEX `fk_notifiaction_users_idx` (`users_IDuser` ASC),
  CONSTRAINT `fk_notifiaction_users`
    FOREIGN KEY (`users_IDuser`)
    REFERENCES `WeatherStations`.`users` (`IDuser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WeatherStations`.`Station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WeatherStations`.`Station` (
  `IDStation` INT NOT NULL,
  `Adress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDStation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WeatherStations`.`weatherResults`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WeatherStations`.`weatherResults` (
  `IDweatherResults` INT NOT NULL,
  `Station_IDStation` INT NOT NULL,
  `Time` DATETIME NOT NULL,
  `Result1` DOUBLE NULL,
  `Result2` DOUBLE NULL,
  `Result3` DOUBLE NULL,
  PRIMARY KEY (`IDweatherResults`, `Station_IDStation`),
  INDEX `fk_weatherResults_Station1_idx` (`Station_IDStation` ASC),
  CONSTRAINT `fk_weatherResults_Station1`
    FOREIGN KEY (`Station_IDStation`)
    REFERENCES `WeatherStations`.`Station` (`IDStation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
